app = "mdf-guide"
primary_region = "iad"

[build]

[env]
  PORT = "8080"
  DATA_DIR = "/data"

[mounts]
  source = "mdf_data"
  destination = "/data"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
